### ISSUE TITLE
0.3dl-r1 version

### ISSUE THREAD

**Issue by Bitroast** [Whitetigerswt/SAMP_AC_v2#205]
Please release the 0.3DL-R1, please!

**Comment by Bitroast** [comment]
:'(

**Comment by iamcharles777** [comment]
Does the 0.3.7 Support this AC? Need it badly :(

**Comment by Whitetigerswt** [comment]
It doesn't support 0.3DL, feel free to open a pull request if you update it.

**Comment by Bitroast** [comment]
anyone? Please guys just convert 0.3.7-R1 to 0.3DL
