### ISSUE TITLE
Client Crash (Stopped Working)

### ISSUE THREAD

**Issue by machete22** [Whitetigerswt/SAMP_AC_v2#208]
Suddenly after no issues in 6 months.We are experiencing this issue and we can't connect to the server.

Problem Event Name:    APPCRASH
  Application Name:    gta_sa.exe
  Application Version:    0.0.0.0
  Application Timestamp:    427101ca
  Fault Module Name:    ACv2_Client.asi
  Fault Module Version:    0.0.0.0
  Fault Module Timestamp:    589d31df
  Exception Code:    c0000005
  Exception Offset:    00078411
  OS Version:    6.1.7601.2.1.0.256.1
  Locale ID:    1033
  Additional Information 1:    dc5f
  Additional Information 2:    dc5f327e098b6d78be55fec952abe1be
  Additional Information 3:    e879
  Additional Information 4:    e879bfb40844151619074cfb38caadf5

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by khalidahmedshalabi** [comment]
Did you solve it? @machete22
