### ISSUE TITLE
Anyone upgraded to 0.3 DL R1?

### ISSUE THREAD

**Issue by Bitroast** [Whitetigerswt/SAMP_AC_v2#211]
It hasn't been updated for 3 years, still no one to update?

**Comment by Bitroast** [comment]
https://github.com/Whitetigerswt/SAMP_AC_v2/issues/205

**Comment by khalidahmedshalabi** [comment]
@Bitroast it might be a good idea to invite someone from the SAMP forums to do it since they're the ones who might be interested I guess. Have a good day

**Comment by Bitroast** [comment]
forum samp is closed, do u know another forum address?

**Comment by khalidahmedshalabi** [comment]
Unfortunately, I don't, but you get the idea
